language: php


php:
    - 7.1


env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi


before_install:
    # Composer self update
    - travis_retry composer self-update


install:
    # Composer install
    - travis_retry composer update --no-interaction --prefer-dist --prefer-stable


script:
    # run Nette Tester
    - vendor/bin/tester tests -p $PHP_BIN -s


after_failure:
    # print *.actual content
    - for i in $(find tests -name *.actual); do echo "--- $i"; cat $i; echo; echo; done


jobs:
    include:
        -   stage: Code Coverage

            script:
                # run Nette Tester for tests coverage
                - vendor/bin/tester tests -s -p phpdbg --coverage coverage.xml --coverage-src src

            after_script:
                # Coveralls report
                - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
                - php coveralls.phar --verbose --config tests/.coveralls.yml


        -   stage: Code Standard Checker

            install:
                # install Nette Code Checker
                - travis_retry composer create-project nette/code-checker temp/code-checker ^2.11 --no-interaction

            script:
                # run Nette Code Checker
                - php temp/code-checker/src/code-checker.php --short-arrays --strict-types

                # run Nette Coding Standard checker
                - composer cs

    allow_failures:
        -   stage: Code Coverage


sudo: false


cache:
    directories:
        - $HOME/.composer/cache


notifications:
    email: false
