language: php

php:
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
    - composer self-update

install:
    - composer install --no-interaction --prefer-source

script: ./vendor/bin/tester ./tests/HarmimTests/

after_failure:
    - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
