name: Coding Style

on: [push, pull_request]

jobs:
  code-checker:
    name: Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make code-checker CI=1

  coding-standard:
    name: Coding Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make coding-standard CI=1
